### ISSUE TITLE
item File(s) Size (KB) unit error

### ISSUE THREAD

**Issue by softxiang** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#14]
item return KB，but your unit is B

**Comment by MantasTumenas** [comment]
Yes, it does. There is a custom multiplier (by 1024), which let's automatically convert B>KB>MB>GB>TB and so on. If you prefer to have, lets say database size, in B instead of GB (TB). Go to item prototype>Preprocessing and remove Custom multiplier.
![image](https://user-images.githubusercontent.com/47737420/58310289-f36a9080-7e0e-11e9-94d4-77c228d3b32e.png)

**Comment by softxiang** [comment]
ok thanks,I've already done that.
