### ISSUE TITLE
Powershell version

### ISSUE THREAD

**Issue by JulioQc** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#24]
Powershell scripts don't work on 2008R2 (MSSQL 2014) with built-in powershell 2.0

  3164:20191101:093524.568 EXECUTE_STR() command:'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\mydb\ZabbixScripts\Discovery.mssql.instanceagentname.ps1"' len:504 cmd_result:'The term 'ConvertTo-'
  3164:20191101:093524.568 for key [agent.mssql.discovery] received value [The term 'ConvertTo-Json' is not recognized as the name of a cmdlet, function, 

Tested after installing WMF 5.1 (PS 5.1) and works as expected. Maybe add to documentation? 
Thanks for great template otherwise!

**Comment by MantasTumenas** [comment]
Hello. I knew that you (as an user) need PS 3.0 for the scripts to work, but did not mentioned it because PS 3.0 comes with:
- Windows Server 2008 with Service Pack 1.
- Windows Server 2008 R2 with Service Pack 1.

I just wrote that these templates were tested on MSSQL2012 (and higher). MSSQL2012 requires at least Windows Server 2008 (and higher). And I assumed that you (as an user) will have your OS updated to latest patch and have PS 3.0.
In any case I will update documentation to avoid any confusion. Thanks for the recommendations
