### ISSUE TITLE
Not working in Zabbix Version  5.4.3

### ISSUE THREAD

**Issue by lselvakumaran** [MantasTumenas/Zabbix-template-for-Microsoft-SQL-Server#39]
Not working in Zabbix Version  5.4.3. No data caputred. We configured as per the attached PDF file. zabbix agent version is 5.4.4. Kindly suggest the same

**Comment by MantasTumenas** [comment]
Tested on Zabbix 3.4.0. and 4.0.0. only. Not tested on 5.0.0. Will have Zabbix 5.x.x. only next week and will check the issue only then.
Also - too little information. What does zabbix agent log show? what does discovery tab show? what does items tab show?

**Comment by MantasTumenas** [comment]
Tested for 2 weeks on Zabbix 5.0.15. No issues reported so far. Does your issue still persist?
What does zabbix agent log show? what does discovery tab show? what does items tab show?

**Comment by IlyaSapytskiy** [comment]
i'm trying to install on zabbix 5.4.6 test server and there is no "Import value mappings via Administration >> General >> Value mapping:" since 5.4. They are moved to template or host level. https://www.zabbix.com/documentation/current/manual/config/items/mapping
Where i have to import value mappings now?

**Comment by MantasTumenas** [comment]
IlyaSapytskiy, I am still on Zabbix 5.0.15. Since, as You wrote, they are moved to template or host level from 5.4, You have these options:
1. Wait till I update templates till 5.4.6. Probably next year only.
2. Or enter value mapping to the templates Yourself. You can open value mapping xml with any txt editor and see values and their mapping. And then add to the template.
